nginx:
  build: build/nginx
  command: nginx -g "daemon off;"
  links:
    - php
  ports:
    - "8080:80"
php:
  build: build/php
  volumes:
    - ./src:/var/www/html
  working_dir: /var/www/html/public
  command: php-fpm
  ports:
    - "9000:9000"
  environment:
    APP_ENV: local
    APP_DEBUG: 'true'
    APP_KEY: SomeRandomKey!!!
    APP_LOCALE: en
    APP_FALLBACK_LOCALE: en
composer:
  restart: 'no'
  image: composer
  volumes:
    - ./src:/app